baseurl = "/"
title = "CrowderSoup"
languageCode = "en-us"
paginate = "10"        # Number of items per page
theme = "soup"      # https://github.com/vimux/binario#configuration

[Author] # Used in authorbox
name = "Aaron Crowder"
nickname = "CrowderSoup"
avatar = "dude_square.png"

[Params]
copyright = "Aaron Crowder"             # Copyright holder, also used in .Site.Title
mainSections = ["posts"]
dateFormat = "January 02, 2006"

[Params.elsewhere]
email = "aaron.crowder@gmail.com"
twitter = "CrowderSoup"
mastodon = "https://hachyderm.io/@CrowderSoup"
telegram = "CrowderSoup"
github = "CrowderSoup"

[outputs]
home = ["HTML", "RSS"]
