baseurl = "/"
title = "CrowderSoup"
languageCode = "en-us"
paginate = "10"        # Number of items per page
theme = "soup"      # https://github.com/vimux/binario#configuration

[Author] # Used in authorbox
name = "Aaron Crowder"
url = "https://crowdersoup.com"
nickname = "CrowderSoup"
avatar = "dude_square.png"

[Params]
copyright = "Aaron Crowder"
mainSections = ["posts"]
dateFormat = "January 02, 2006"
description = "A website about programming, technology, and life."
authorization_endpoint = "https://indieauth.com/auth"
token_endpoint = "https://tokens.indieauth.com/token"
microsub = "https://aperture.p3k.io/microsub/205"

[Params.elsewhere]
email = "aaron.crowder@gmail.com"
twitter = "CrowderSoup"
mastodon = "https://hachyderm.io/@CrowderSoup"
telegram = "CrowderSoup"
github = "CrowderSoup"

menu = ['main']

[outputs]
home = ["HTML", "RSS"]
