name = "Soup"
license = "MIT"
licenselink = "https://github.com/crowdersoup/crowdersoup.com/themes/soup"
description = "Responsive card-based & code-light Hugo theme"
homepage = "https://github.com/crowdersoup/crowdersoup.com/"
demosite = "https://crowdersoup.com"
tags = ["blog", "dark", "minimal"]
features = []
min_version = "0.54.0"

[author]
  name = "CrowderSoup"
  homepage = "https://crowdersoup.com"
